"""
Run report generator for CheckPilot.
Creates HTML/CSV report after each automation run.
"""
import os
import csv
from datetime import datetime
from typing import List
from config import DATA_DIR

REPORTS_DIR = os.path.join(DATA_DIR, "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_report(
    template: str,
    site: str,
    inspection_date: str,
    total_items: int,
    items_ok: int,
    items_failed: int,
    errors: List[str],
    images_uploaded: int,
    images_failed: int,
    submitted: bool,
    mode: str,
    duration_sec: float,
    data_file: str = "",
) -> str:
    """Generate HTML report. Returns file path."""
    ts = datetime.now()
    filename = f"report_{ts.strftime('%Y%m%d_%H%M%S')}_{template[:20].replace(' ','_')}.html"
    filepath = os.path.join(REPORTS_DIR, filename)

    status = "SUBMITTED" if submitted else ("TEST MODE" if mode == "test" else "BLOCKED")
    status_color = "#15803D" if submitted else ("#B45309" if mode == "test" else "#B91C1C")

    errors_html = ""
    if errors:
        errors_html = "<h3>Errors</h3><ul>"
        for e in errors:
            errors_html += f"<li>{_esc(e)}</li>"
        errors_html += "</ul>"

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>CheckPilot Report - {_esc(template)}</title>
<style>
body {{ font-family: 'Segoe UI', sans-serif; background: #F7F9FC; color: #172033; padding: 30px; }}
.card {{ background: #FFFFFF; border: 1px solid #D7DEE8; border-radius: 8px; padding: 20px; margin-bottom: 16px; }}
h1 {{ color: #0F766E; margin: 0 0 5px 0; }}
h2 {{ color: #44546A; font-size: 14px; font-weight: normal; margin: 0 0 20px 0; }}
h3 {{ color: #172033; font-size: 13px; margin: 12px 0 8px 0; }}
.status {{ display: inline-block; padding: 4px 12px; border-radius: 4px; font-weight: bold; font-size: 13px; background: {status_color}20; color: {status_color}; border: 1px solid {status_color}; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
td {{ padding: 6px 12px; border-bottom: 1px solid #D7DEE8; font-size: 12px; }}
td:first-child {{ color: #7A8699; width: 140px; }}
ul {{ margin: 5px 0; padding-left: 20px; }}
li {{ color: #B91C1C; font-size: 12px; margin: 3px 0; }}
.footer {{ margin-top: 20px; font-size: 10px; color: #7A8699; text-align: center; }}
</style></head><body>
<h1>CheckPilot Report</h1>
<h2>Inspection Automation Report</h2>

<div class="card">
<span class="status">{status}</span>
<table>
<tr><td>Template</td><td><b>{_esc(template)}</b></td></tr>
<tr><td>Site</td><td>{_esc(site)}</td></tr>
<tr><td>Date</td><td>{_esc(inspection_date)}</td></tr>
<tr><td>Run time</td><td>{ts.strftime('%d/%m/%Y %H:%M:%S')}</td></tr>
<tr><td>Duration</td><td>{duration_sec:.1f}s</td></tr>
<tr><td>Mode</td><td>{mode.upper()}</td></tr>
<tr><td>Data file</td><td>{_esc(os.path.basename(data_file))}</td></tr>
</table>
</div>

<div class="card">
<h3>Results</h3>
<table>
<tr><td>Total items</td><td>{total_items}</td></tr>
<tr><td>Items OK</td><td style="color:#15803D">{items_ok}</td></tr>
<tr><td>Items failed</td><td style="color:#B91C1C">{items_failed}</td></tr>
<tr><td>Images uploaded</td><td>{images_uploaded}</td></tr>
<tr><td>Images failed</td><td style="color:#B91C1C">{images_failed}</td></tr>
</table>
</div>

{errors_html}

<div class="footer">
Generated by CheckPilot v2.2 | Designed by Phạm Duy | 0868609901
</div>
</body></html>"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)

    return filepath


def generate_summary_csv(records: List[dict]) -> str:
    """Generate summary CSV from multiple run records."""
    ts = datetime.now().strftime('%Y%m%d_%H%M%S')
    filepath = os.path.join(REPORTS_DIR, f"summary_{ts}.csv")

    with open(filepath, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(["Timestamp", "Template", "Site", "Date", "Items", "OK", "Failed",
                         "Submitted", "Mode", "Errors"])
        for r in records:
            writer.writerow([
                r.get("timestamp", ""),
                r.get("template", ""),
                r.get("site", ""),
                r.get("inspection_date", ""),
                r.get("total_items", 0),
                r.get("items_ok", 0),
                r.get("items_failed", 0),
                r.get("submitted", False),
                r.get("mode", ""),
                "; ".join(r.get("errors", [])),
            ])

    return filepath


def get_reports_dir() -> str:
    return REPORTS_DIR


def _esc(s: str) -> str:
    """HTML escape."""
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
